"""user tokens

Revision ID: cdc7837b48ed
Revises: 28d3f0c916e1
Create Date: 2021-08-18 12:06:09.641797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc7837b48ed'
down_revision = '28d3f0c916e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_column('users', 'token')
    op.drop_column('users', 'token_expiration')
    # ### end Alembic commands ###
